[build]
  command = "npm run front:build"
  publish = "dist"
  functions = "netlify"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/todo"
  to = "https://github.com/resync-tv/resync/projects/2?fullscreen=true"
  status = 301

[[redirects]]
  from = "/git"
  to = "https://github.com/resync-tv/resync"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200